# Site settings
title: Blog QVAPRO
subtitle: Red de Profesionales de Cuba
email: contacto@qvapro.com
description: > # this means to ignore newlines until "baseurl:"
              QvaPro ofrece empleos a la comunidad profesional cubana. Pretendemos ser el primer punto de encuentro
              entre el mejor capital cubano y empresas o negocios emergentes.
author: Blog QVAPRO | Red de Profesionales de Cuba
baseurl: ""
url: "http://blog.qvapro.com"
twitter_username: qvapro
# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more-->
production: true
lsi: false
gems:
 - jekyll-sitemap
 - jemoji
sass:
  style: :compressed
paginate: 4
paginate_path: "/pagina/:num"